package ES;


/**
* ES/end.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionEnd.idl
* Tuesday, March 6, 2018 2:13:50 PM PST
*/

public interface end extends endOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface end
