package ES;


/**
* ES/endHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionEnd.idl
* Tuesday, March 6, 2018 2:13:50 PM PST
*/

abstract public class endHelper
{
  private static String  _id = "IDL:ES/end:1.0";

  public static void insert (org.omg.CORBA.Any a, ES.end that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ES.end extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ES.endHelper.id (), "end");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ES.end read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_endStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ES.end value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ES.end narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ES.end)
      return (ES.end)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ES._endStub stub = new ES._endStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ES.end unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ES.end)
      return (ES.end)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ES._endStub stub = new ES._endStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
