package ES;

/**
* ES/endHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionEnd.idl
* Tuesday, March 6, 2018 2:13:50 PM PST
*/

public final class endHolder implements org.omg.CORBA.portable.Streamable
{
  public ES.end value = null;

  public endHolder ()
  {
  }

  public endHolder (ES.end initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ES.endHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ES.endHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ES.endHelper.type ();
  }

}
