package ES;


/**
* ES/endOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionEnd.idl
* Tuesday, March 6, 2018 2:13:50 PM PST
*/

public interface endOperations 
{
  void view_auction (String username, org.omg.CORBA.StringHolder c);
  void sell (String username, String itemname, int price, org.omg.CORBA.StringHolder c);
  void bid (String username, int price, org.omg.CORBA.StringHolder c);
  void view_high_bidder (String username, org.omg.CORBA.StringHolder name, org.omg.CORBA.StringHolder c);
  void view_bid (String username, org.omg.CORBA.StringHolder output);
  void offer_item (String username, String itemname, int price, org.omg.CORBA.StringHolder c);
} // interface endOperations
